### PR TITLE
Layout feature

### PR DESCRIPTION
**Pull request by jedireza**
Related to #53 📟 @abritinthebay 

 - No longer using `PLACEHOLDER` constant
 - Removed the `layoutKeyword` option
 - Fixed bug where HTML doctype wasn't part of the final output
 - Layouts must use `dangerouslySetInnerHTML={{ __html: this.props.children }}` to place the view content
 - The same `context` is passed to both the layout and the view and isn't duplicated/copied
 - Copied old `examples/layout` to `examples/layout-component`
 - Updated `examples/layout` and `examples/remount` to use the new layout feature
 - Added an event test to `examples/remount`
 - Fixed `lab` to fail CI if code coverage is below 100%
 - Updated dependencies `hoek@4`, dev dependencies `inert@4`
 - Removed caching options in Travis config

To finish this up:

 - [x] Update README with new examples, documentation
 - [x] Add tests

### CODE REVIEW

**Comment by abritinthebay** [comment]
oh nice. I like the solution using `dangerouslySetInnerHTML, that's nice and clean. Not sure why I didn't use that originally.

**Comment by abritinthebay** [comment]
Looks like Vision/Hoek updated and is breaking your tests.

**Comment by jedireza** [comment]
Besides code coverage failing, locally tests running are passing. I restarted Travis to see what's up.

**Comment by jedireza** [comment]
Ok it may have been some caching features added to the Travis config a while ago. I removed those and now we're just failing because of code coverage. 😉

**Comment by jedireza** [comment]
Once the build passes we should be good to go. @abritinthebay would be willing to give things a final review? Thoughts on the docs?

**Comment by abritinthebay** [comment]
Docs look good - little sparse but combined with the examples I think it's reasonably clear. Seems solid.

**Pull request merged**
