### PR TITLE
Add support for react 14

### PR DESCRIPTION
**Pull request by tkh44**
Use ReactDOMServer to render server side markup.

I'm not sure how to handle legacy support.  Any ideas?

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks for creating a PR! I'd like to hold off on releasing this until `0.14` is out of `rc` status. Since upgrading to `0.14` will be a breaking change we'll bump our major anyways. People could always use the other versions.

**Comment by tkh44** [comment]
Sounds good.  When 14 is released I'll update the package.json.

**Comment by jedireza** [comment]
Closing this PR for now.

**Comment by jedireza** [comment]
And right after I close this, I see the tweets and blog post about React `0.14` proper :smile: haha. Feel free to update this PR.

**Comment by bbondy** [comment]
Can this be landed? Thanks!

**Comment by ark4innovation** [comment]
As part of React 0.14 support, is there a plan to also switch from node-jsx to babel?

**Comment by jedireza** [comment]
@tkh44 I submitted a minor patch to your fork.

@bbondy yes. We're just about there.

@ark4innovation I would like to use babel instead. Would you be willing to create a PR for that?

**Comment by tkh44** [comment]
@jedireza I merged it.

**Comment by jedireza** [comment]
@tkh44 ok great! Let's squash the commits into one that reads `Add support for react 14` (your original commit message).

If you need help with squashing commits see:

 - https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
 - http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by jedireza** [comment]
:pager: We should get this change landed soon.

**Comment by tkh44** [comment]
@jedireza Should be good now.

**Comment by jedireza** [comment]
:shipit: Thanks!

**Pull request merged**
